name: SERVER-API-COVERAGE

on:
  push:
    paths:
      - server/services/api
    branches: [main, dev]
  pull_request:
    paths:
      - server/services/api
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./server/services"

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Nest.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: services
        run: |
          cd ./api
          npm install
          npm run coveralls

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./server/services/api/coverage/lcov.info
