name: SERVER-DEPLOY

on: [push, pull_request]

jobs:
  build:
    name: Deploy MSA
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./server"

    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Execute Docker-Compose
        run: docker-compose up -d

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
